apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: harrissaif01/backend:latest
        ports:
        - containerPort: 5000  # Backend listens on port 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000      # Expose port 5000
      targetPort: 5000 # Target port on container
  clusterIP: None     # To enable headless service if needed for direct communication between pods
